# Default values for feature-toggle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: leobozcaitano/feature-toggle
  tag: latest
  pullPolicy: Always

nameOverride: "feature-toggle"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

hpa:
  enabled: false
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 95

resources:
  limits:
    cpu: 640m
    memory: 1536Mi
  requests:
    cpu: 300m
    memory: 1536Mi

livenessProbe:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 100
  timeoutSeconds: 10
  failureThreshold: 10
readinessProbe:
  enabled: true
  path: /actuator/health/readiness
  initialDelaySeconds: 60
  timeoutSeconds: 10

terminationGracePeriodSeconds: 60

env:
  - name: "ELASTIC_APM_ENVIRONMENT"
    value: "dev"

environmentVariables:
  - name: MONGO_URI
    value: "http://mongodb:27017"