name: Run tests and build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Composing the infrastructure
      run: docker-compose up -d && sleep 3
    
    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
