name: Run tests and build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Composing the infrastructure
      run: docker-compose up -d && sleep 3

    - name: Build
      run: go build -v ./...

    - name: DockerHub Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Building the image
      run: docker build . --tag ${{secrets.DOCKER_USER}}/feature-toggle

    - name: Push image to dockerhub
      run: docker push ${{secrets.DOCKER_USER}}/feature-toggle
